#!/bin/bash
set -e

docker build . -t swift-cross-aarch64:__test
docker run --rm \
    -v=$PWD/Tests:/swift \
    -w=/swift \
    swift-cross-aarch64:__test \
    swift build -c release --destination aarch64-unknown-linux-gnu.json
