#!/bin/bash
set -e

docker build . -t swift-cross-aarch64:__test

# Test dynamically linked standard library
docker run --rm \
    -v=$PWD/Tests:/swift \
    -w=/swift \
    swift-cross-aarch64:__test \
    /home/ubuntu/x86_64/swift/usr/bin/swift \
        build -c release \
        --destination aarch64-unknown-linux-gnu.json

# Test statically linked standard library
docker run --rm \
    -v=$PWD/Tests:/swift \
    -w=/swift \
    swift-cross-aarch64:__test \
    /home/ubuntu/x86_64/swift/usr/bin/swift \
        build -c release \
        --destination aarch64-unknown-linux-gnu.static.json \
        --static-swift-stdlib
